name: Build windows static binary
on:
  workflow_dispatch:

jobs:
  build-sane_in_the_membrane-gui:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install dev tools
        run: |
          choco install nasm ninja cmake -y

      - name: Enable Developer Command Prompt (Windows)
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: Cache CMake build
        uses: actions/cache@v5
        with:
          path: build
          key: ${{ runner.os }}-cmake-build-static-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-cmake-build-static-

      - name: Configure
        shell: pwsh
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DSTATIC_WINDOWS_BUILD=ON -GNinja

      - name: Build
        shell: pwsh
        run: cmake --build build --parallel

      - name: Upload artifact (Windows - binary)
        uses: actions/upload-artifact@v6
        with:
          name: Gui-Windows
          path: build/gui-app/Gui.exe
